apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: IMAGE_URL_PLACEHOLDER_API
        ports:
        - containerPort: 3000
        env:
          - name: DB
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 3000
