name: Build, Push and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    name: Build, Push to ECR, and Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Web Docker image
        run: |
          WEB_IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_WEB_REPOSITORY }}:${{ github.sha }}"
          docker build -t $WEB_IMAGE_URI -f devops-challenge-apps/web/Dockerfile ./devops-challenge-apps/web
          docker push $WEB_IMAGE_URI
          echo "WEB_IMAGE_URI=$WEB_IMAGE_URI" >> $GITHUB_ENV

      - name: Build and Push API Docker image
        run: |
          API_IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_API_REPOSITORY }}:${{ github.sha }}"
          docker build -t $API_IMAGE_URI -f devops-challenge-apps/api/Dockerfile ./devops-challenge-apps/api
          docker push $API_IMAGE_URI
          echo "API_IMAGE_URI=$API_IMAGE_URI" >> $GITHUB_ENV

      - name: Set up Kubeconfig
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ARN_OF_YOUR_IAM_ROLE_FOR_EKS
          role-duration-seconds: 1200
          role-session-name: my-github-actions-session
          save-to-file: true # Saves the configured credentials as the default kubeconfig file.

      - name: Deploy to EKS
        run: |
          sed -i "s|IMAGE_URL_PLACEHOLDER_WEB|$WEB_IMAGE_URI|g" ./k8s/web-app.yaml
          sed -i "s|IMAGE_URL_PLACEHOLDER_API|$API_IMAGE_URI|g" ./k8s/api-app.yaml
          kubectl apply -f ./k8s/web-app.yaml
          kubectl apply -f ./k8s/api-app.yaml

